apiVersion: {{ .Values.apiVersion }}
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}
    spec:
      containers:
      - name: {{ .Values.deploymentName }}
        image: {{ .Values.image }}
        env:
        - name: ACCEPT_EULA
          value: {{ .Values.acceptEula }}
        - name: ADMIN_USERNAME
          value: {{ .Values.ADMIN_USERNAME }}
        - name: ADMIN_PASSWORD
          value: {{ .Values.ADMIN_PASSWORD }}
        - name: DB_CONNECTION_STRING
          value: {{ .Values.DB_CONNECTION_STRING }}
        - name: MASTER_KEY
          value: {{ .Values.MASTER_KEY }}
        - name: ADMIN_EMAIL
          value: {{.Values.email}}
        - name: OCTOPUS_SERVER_BASE64_LICENSE
          value: {{ .Values.OCTOPUS_SERVER_BASE64_LICENSE }}
        ports:
        - containerPort: {{ .Values.containerPort }}

        volumeMounts:
          - name: tasklogs
            mountPath: /taskLogs
          - name: artifacts
            mountPath: /artifacts
          - name: repository
            mountPath: /repository
            
      livenessProbe:
        exec:
          command:
            - /bin/bash
            - -c
            - URL=http://localhost:8080; response=$(/usr/bin/curl -k $URL/api/octopusservernodes/ping --write-out %{http_code} --silent --output /dev/null); /usr/bin/test "$response" -ge 200 && /usr/bin/test "$response" -le 299 || /usr/bin/test "$response" -eq 418

      volumes:
        - name: tasklogs
          persistentVolumeClaim:
            claimName: task-logs-claim
        - name: repository
          persistentVolumeClaim:
            claimName: repository-claim
        - name: artifacts
          persistentVolumeClaim:
            claimName: artifacts-claim