kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: repository-claim
spec:
  # If you are using one replica, ensure the accessMode value is -ReadWriteOnce
  # If you have more than one replica, ensure the accessMode value is -ReadWriteMany
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifacts-claim
spec:
  # If you are using one replica, ensure the accessMode value is -ReadWriteOnce
  # If you have more than one replica, ensure the accessMode value is -ReadWriteMany
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-logs-claim
spec:
  # If you are using one replica, ensure the accessMode value is -ReadWriteOnce
  # If you have more than one replica, ensure the accessMode value is -ReadWriteMany
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 1Gi