kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: repository-claim
spec:
  # If you are using one replica, ensure the accessMode value is -ReadWriteOnce
  # If you have more than one replica, ensure the accessMode value is -ReadWriteMany
  accessModes:
    - ReadWriteMany
  # {{ .Values.storageAccessModeManyReplicas }}
  # {{- if (eq "-" (.Values.storageClassName | toString)) }}
  # {{- else if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  # {{- end }}
  resources:
    requests:
      storage: 1Gi
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: artifacts-claim
# spec:
#   accessModes:
#     {{- if (gt (.Values.replicaCount | int) 1)}}
#     - ReadWriteMany
#     {{- else }}
#     - {{.Values.storageAccessMode}}
#     {{- end }}
#   {{- if (eq "-" (.Values.storageClassName | toString)) }}
#   storageClassName: ""
#   {{- else if .Values.storageClassName }}
#   storageClassName: "{{ .Values.storageClassName }}"
#   {{- end }}
#   resources:
#     requests:
#       storage: 1Gi
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: task-logs-claim
# spec:
#   accessModes:
#     {{- if (gt (.Values.replicaCount | int) 1)}}
#     - ReadWriteMany
#     {{- else }}
#     - {{.Values.storageAccessMode}}
#       {{- end }}
#   {{- if (eq "-" (.Values.storageClassName | toString)) }}
#   storageClassName: ""
#   {{- else if .Values.storageClassName }}
#   storageClassName: "{{ .Values.storageClassName }}"
#   {{- end }}
#   resources:
#     requests:
#       storage: 1Gi