apiVersion: v1
kind: Service
metadata:
  name: octopus-web
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  {{- if (eq (.Values.replicaCount | int) 1)}}
    # If there is only one node, expose the tentacle along with the web port
    - name: tentacle
      port: 10943
      targetPort: 10943
      protocol: TCP
  {{- end }}
  selector:
    app: octopus
{{- if .Values.exposeServices }}
{{- $root := . -}}
{{- range untilStep 0 ( .Values.replicaCount | int) 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: octopus-{{ . }}
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: 80
    name: web
    targetPort: 8080
    protocol: TCP
  - port: 10943
    name: tentacle
    targetPort: 10943
    protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: octopus-{{ . }}
{{- end }}
{{- end }}